version: "3"

services:

  random:
    build: random
    ports:
      - 8000:8080
    environment:
      FLASK_APP: main

  visits:
    build: visits
    ports:
      - 8001:8080
    environment:
      FLASK_APP: main

  telemetry:
    build: telemetry
    ports:
      - 8002:8080
    environment:
      FLASK_APP: main
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
