version: "3"

services:

  random:
    build: random
    ports:
      - 8000:8080
    environment:
      FLASK_APP: main

  visits:
    build: visits
    ports:
      - 8001:8080
    environment:
      FLASK_APP: main

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
